### ISSUE TITLE
[bug] wheels don't work on Mac OSX without libgfortran installed

### ISSUE THREAD

**Issue by asreimer** [aburrell/apexpy#10]
Unable to use `apexpy` after installing on the latest OSX using `pip`. Also using anaconda, but that shouldn't matter since the error seems to be a missing shared library.

Installed `apexpy` using `pip`:

    $ pip install apexpy

Then tried to import the `Apex` class:

    >>> from apexpy import Apex
    ERROR: fortranapex module could not be imported. apexpy probably won't work

As you can see, pip installed `apexpy` just fine, but the `fortranapex` module failed to import properly. Why is that? Let's find out:

    >>> import apexpy
    >>> import os, sys
    >>> sys.path.append(os.path.dirname(apexpy.__file__))
    >>> import fortranapex
    
    Traceback (most recent call last):
      File "<ipython-input-42-1a6503a9c53b>", line 1, in <module>
        import fortranapex
    
    ImportError: dlopen(/Users/admin.e32063/anaconda2/lib/python2.7/site-packages/apexpy/fortranapex.so, 2    ): Library not loaded: /opt/local/lib/libgcc/libgfortran.3.dylib
      Referenced from: /Users/admin.e32063/anaconda2/lib/python2.7/site-packages/apexpy/fortranapex.so
      Reason: image not found

Ah! We didn't install gcc and gfortran on our Mac. ~~But we shouldn't have to if we are using wheels!~~ Nope, this is only true if libgfortran was also packaged in the wheel. As you can see, the issue is that the fortranapex.so library is looking for the `/opt/local/lib/libgcc/libgfortran.3.dylib` library that it was dynamically linked against. If you have brew (I think?) installed on your Mac, then you won't have this problem, but if you don't, you need to install brew and then install gcc and gfortran.

So I think the solutions are:
1) Change the requirements of apexpy to require the user to install brew and gcc gfortran under OSX. This sucks, because it defeats the purpose of the whole wheels system that pip uses.
2) Change the [Makefile in fortranapex](https://github.com/aburrell/apexpy/blob/master/src/fortranapex/Makefile) to statically link the fortranapex.so library so that it doesn't need to depend on external libraries.

**Comment by aburrell** [comment]
Yay for updates in the operating system :(

I'll look into the second suggestion this week.  May I ping you for a test when I get it working?

Cheers!

**Comment by asreimer** [comment]
I'm really not great with Makefiles, but I think the solution is to add `-static-libgfortran` to the `LDFLAGS` of the [fortranapex makefile](https://github.com/aburrell/apexpy/blob/master/src/fortranapex/Makefile).

See: https://stackoverflow.com/questions/30545272/how-to-compile-fortran-code-to-run-without-gfortran-installed

I don't think this is related to updates in the operating system, but instead a hidden assumption that one must have gfortran installed.

Unfortunately, I don't have a mac that I can do the compilation on, but if you email me the `fortranapex.so` binary, I can try testing it on the Mac that had the bug!

**Comment by asreimer** [comment]
It just occurred to me that this bug should occur in Linux too if you don't have `libgfortran` installed.

So I tested this on a Cent OS7 virtual machine. Without the system package `libgfortran` installed, I got the same error! That means I can test fixing this without need OS X.

So I ran some tests modifying the Makefile and was able to get the following changes to work:

1) `LDFLAGS = -static-libgfortran`
2) `FFLAGS = -O3 -fPIC -static-libgfortran`

But that's in the Makefile, which isn't used by `setup.py`...

After trial and error, I found that the following worked for the setup.py:

    LDFLAGS='-static-libgfortran' FFLAGS='-O3 -fPIC -static-libgfortran' pip install .

Note that you can check what  a libraries a shared library depends on using the `ldd` command. If you successfully included `libgfortran` in the `fortranapex.so` then the output of `ldd fortranapex.so` shouldn't include `libgfortran in it.

So a potential solution to this problem is to add:

    environ['LDFLAGS']='-static-libgfortran'
    environ['FFLAGS']='-O3 -fPIC -static-libgfortran'

in to the `setup.py` file right after the `from numpy.distutils.core import setup, Extension` inside the `if ... else` statement.

**Comment by aburrell** [comment]
No, I use port or just go and install things the old fashioned way.  I'm not a fan of requiring people to use port/brew/anaconda/pip whatever.  I'm going to go take a look at your pull request now.

**Comment by aburrell** [comment]
So, it turns out that mac's don't like static linking.  I've had limited luck with static linking on linux, too.  Right now I'm going to address this issue by clarifying in the README that you need to have gfortran installed, even for wheels.

To make things better in the future, I opened up the static branch.  In this branch I altered the makefile to add a static flag if you do: make STATIC=1 (or STATIC=anything other than zero).  I then added some logic to the setup.py so that it flags STATIC=1 if you are not on a mac and bdist_wheel is true.

I couldn't get the static compilation to work on either of the machines I have access to.  Could you give it a try?  No need to mess with the setup.py, just try

`make STATIC=1`

in the apexpy/src/fortranapex directory.

**Comment by asreimer** [comment]
> I'm very surprised you didn't have gcc installed. 

Student computer. I don't have a mac to test things on, although that should be changing soon<sup>TM</sup> with a VM I'm working on setting up. That being said, this isn't just an isolated problem with Macs. If you don't have libgfortran installed in linux, you can't run apexpy either. This is nice because it means we can test static compiling on linux and if it works there it might work on the mac too. I wonder how this works in windows? Using anaconda?

Anyway, I've tried statically compiling the library and succeeded. The issue though (as I mentioned here: https://github.com/aburrell/apexpy/pull/11#issuecomment-402002212, although I wasn't super clear) is that the library is compiled using f2py and if you compile using f2py, the makefile isn't used. Also, statically compiling with f2py (by setting LDFLAGS=-static-libgfortran and FFLAGS=-O3 -fPIC -static-libgfortran) results in a fortranapex.so that can't be dynamically loaded by python. For example, try this:

    LDFLAGS='-static-libgfortran' FFLAGS='-O3 -fPIC -static-libgfortran' pip install .

for the master branch. Then:

    from apexpy import fortranapex

gives:

    ImportError: /path/to/site-packages/apexpy/fortranapex.so: cannot dynamically load executable

I've checked, and this isn't a permissions issue. It's something I don't quite understand about how -static-libgfortran interacts with f2py.

I also tested running `make STATIC=1` as you suggested, but on my linux machine. You need to make sure you have glibc-static installed if you want it to succeed. I can build the library just fine, but that doesn't help me install it. All this does is create an `apextest` binary in the `src/fortranapex/` directory. What does this do for us? If the goal is to compile the entire library as static, this won't work in general for the setup.py, because that requires a static python library (which you need to compile yourself from scratch, since I don't think it's a standard think available in most package managers). And really, all we need is libgfortran and libquadmath to be statically compiled in to the library, everything else can be dynamically loaded. However, this could help us if we statically compiled the library and then wrapped it using ctypes instead of f2py...

Which leads to:

> Right now I'm going to address this issue by clarifying in the README that you need to have gfortran installed, even for wheels.

I agree with where you are going with this. I think in the interests of time, it is best to simply provide documentation on how to work around a known issue for a small subset of users. I will suggest that the README instead say something like
1) You need to have libgfortran and libquadmath installed on your machine
2) If on a Mac, the PyPI wheel is built using (macports?) so you need to either install libgfortran using macports, or make a symbolic link in /opt/lib/libgcc/ pointing to where you have libgfortran installed. You also need to do the same for libquadmath
3) Or, you can install gcc and gfortran inside the anaconda environment and then build apexpy yourself with `pip install .`. (https://anaconda.org/anaconda/gcc, https://anaconda.org/anaconda/gfortran_osx-64, and https://anaconda.org/conda-forge/libgfortran)

because the issue isn't whether someone has gfortran installed, it's whether they have libgfortran installed (and libquadmath).

Sorry I wasn't as clear before. I wasn't really sure what the problem was before...

**Comment by asreimer** [comment]
Oh! The message [here](https://github.com/aburrell/apexpy/blob/master/src/apexpy/apex.py#L17-L18) could be changed so that if the fortranapex library fails to load it points the user at the documentation they need to resolve the issue! That would make the message much more helpful haha.

**Comment by aburrell** [comment]
> the library is compiled using f2py and if you compile using f2py, the makefile isn't used
And this is where my C background got the better of me.  Nice to see that the fix worked, but it's not particularly useful.

> I've checked, and this isn't a permissions issue. It's something I don't quite understand about how -static-libgfortran interacts with f2py.

Yes, I think I alluded to this earlier, but not very clearly.  fortranapex doesn't allow static linking.  This means it's impossible to make a static linking version for Macs.  It is possible with Linux, because you can just use the "-static" flag (if your system is set up to allow it).  No idea about Windows.

> However, this could help us if we statically compiled the library and then wrapped it using ctypes instead of f2py...

I think this is probably the way forward

> If on a Mac, the PyPI wheel is built using (macports?) so you need to either install libgfortran using macports, or make a symbolic link in /opt/lib/libgcc/ pointing to where you have libgfortran installed. You also need to do the same for libquadmath

Yeah... I don't like the idea of making people use brew or macports and symbolic links of libraries into another directory that many users may not know how to make seems like a big barrier.  At this point I'm tempted to take down the wheels until we have an approach like the ctypes solution you mentioned.  Thoughts?

**Comment by aburrell** [comment]
Also, by "fortranapex" I really mean "libquadmath"

**Comment by aburrell** [comment]
Pull request #13 changes in apex.py have a clearer error message.  @asreimer , could you take a look and tell me if it's clear to you?

**Comment by dcsoztrk** [comment]
I think this problem doesn't require a new thread since it is very relevant. I have gcc version 7 installed which comes with libgfortran.4.dylib and libgfortran5.dylib, so the installation fails with the same error, having not found "opt/local/lib/libgcc/libgfortran.3.dylib". I installed gcc version 6 to work around that issue but I was wondering if apexpy was compatible with newer versions?

**Comment by asreimer** [comment]
Hey @dcsoztrk, are you using macports, brew, or conda?

**Comment by asreimer** [comment]
Hey @dcsoztrk, actually, it shouldn't matter what you are using. You should be able to successfully build and install apexpy yourself with:

    pip install --global-option='build_ext' apexpy

as long as you have libgfortran and gfortran installed. Let us know if this works for you. I just tested it myself.

**Comment by dcsoztrk** [comment]
--global-option='build_ext' works, thanks!

**Comment by asreimer** [comment]
Good to hear. We should add this to the readme. I'll make a PR.

**Comment by ljlamarche** [comment]
With much help from @asreimer , here's the installation procedure that worked for me.  I'm on Mac OSX and trying to install apexpy in a new conda environment.

1. Activate conda environment you want to install apexpy in.
```
conda activate apexpy_test_install
```
2. Install the dependencies. (https://anaconda.org/anaconda/gcc, https://anaconda.org/anaconda/gfortran_osx-64, https://anaconda.org/conda-forge/libgfortran)
```
conda install numpy
conda install -c anaconda gcc
conda install -c anaconda gfortran_osx-64
conda install -c conda-forge libgfortran
```
3. Install apexpy from git repo using necessary fortran `LDFLAGS` from the conda-forge scipy-feedstock recipe (https://github.com/conda-forge/scipy-feedstock/blob/master/recipe/build.sh).  Note: because apexpy doesn't have C or C++, you DON'T need those flags.
```
LDFLAGS="-headerpad_max_install_names -undefined dynamic_lookup -bundle -Wl,-search_paths_first" pip install git+https://github.com/aburrell/apexpy.git
```
4. If you're like me and want to install from a branch that's NOT master to have access to new features, just add `@branch_name` at the end of the repo.
```
LDFLAGS="-headerpad_max_install_names -undefined dynamic_lookup -bundle -Wl,-search_paths_first" pip install git+https://github.com/aburrell/apexpy.git@develop
```
