### ISSUE TITLE
Problem with pip installation and long path names

### ISSUE THREAD

**Issue by aburrell** [aburrell/apexpy#2]
I ran into trouble installing and running apexpy on my Mac.  One issue I'm not sure what the problem is, the other one I was able to fix very simply:

1) installing using pip failed with:
Command /usr/bin/python -c "import setuptools, tokenize;__file__='/private/var/folders/jz/syw9ddrj3ds5_j1gcnxdzz6m0000gq/T/pip_build_ab763/apexpy/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/jz/syw9ddrj3ds5_j1gcnxdzz6m0000gq/T/pip-FM9MtN-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /private/var/folders/jz/syw9ddrj3ds5_j1gcnxdzz6m0000gq/T/pip_build_ab763/apexpy
Storing debug log for failure in /Users/ab763/Library/Logs/pip.log

2) I grabbed the source code and did the install myself.  The everything was successful, but I couldn't use the routines because when I tried to initialise the Apex object I received this error:

At line 175 of file src/fortranapex/apexsh.f90 (unit = 23)
Fortran runtime error: Cannot open file '/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/apexpy-1.0.1-py2.7-macosx-10.12-x86_64.e': No such file or directory

Obviously, the path that my computer stored the data file was too long for the character limit allowed in the filename.  I changed the allowed length from 123 characters to 1000 characters in apexsh.f90 (in two places) and now the code runs fine.

Details about my system:
    Your operating system name and version: MacOS Sierra v 10.12.6, python 2.7
    Any details about your local setup that might be helpful in troubleshooting: I usually install things using macports
    Detailed steps to reproduce the bug: use a long path name for the data file

**Comment by cmeeren** [comment]
Hi Angeline, thanks for the detailed bug report. Unfortunately I've left academia some years ago and haven't touched this package since (nor any other Python code, for that matter). Thus, I'm unable to make any significant contributions or fixes to apexpy (and [AACGMv2](https://github.com/cmeeren/aacgmv2)).

If you or anyone else want to take over maintenance of these packages, I'm more than happy to arrange that. In any case, I'm going to leave this bug open.

Nice profile pic, btw. ESR is definitely one thing I miss from my PhD years.

**Comment by aburrell** [comment]
Hi Christer,

I remember that you had left academia, but I wasn’t sure if you were still dabbling with the packages.  Thanks for contacting me, and not leaving the bug report hanging.  I’d be happy to take over the maintenance of these packages for the moment.  I’m working with some people (who have funding!) to develop a cohesive space physics python package.  So even if I don’t end up doing the maintenance myself, I’ll be able to ensure that the work you’ve done on these doesn’t need to be repeated.

Thanks!  That picture was a lot of fun :->

Cheers,
Angeline

**Comment by cmeeren** [comment]
Thanks! Should I go ahead and transfer this repo and AACGMv2 to your user?

**Comment by cmeeren** [comment]
Also, I'll need your PyPI username to add you as an owner so you can publish updates.

**Comment by aburrell** [comment]
Yes, go ahead and transfer apexpy and AACGMv2 to my user.  Here is my PyPI user name: aburrell.  Let me know if there’s anything else you need.

Cheers,
Angeline

**Comment by cmeeren** [comment]
Done. It would be great if you could give me your username (or register) at readthedocs.org, where the documentation is.

As for deployment, I've linked the repo with AppVeyor and Travis so that all tests are run for each commit. Travis tests on Linux and AppVeyor on Windows. Tagged commits are automatically pushed to PyPI from AppVeyor if tests succeed (that's where the compiled PyPI binaries come from). This requires the AppVeyor environment variables `PYPI_USER` and `PYPI_PASS` to be set to your PyPI username/password.

I have no idea if the deployment still works (it's been a while since the last deployment) or what happens now that things are transferred, but if you too want to have automated deployment you should be able to set things up fairly easily (hopefully) using your own accounts. I'll delete my stuff at AppVeyor and Travis.

**Comment by aburrell** [comment]
Thanks Christer!

My username at readthedocs is also aburrell.

I was unaware of AppVeyor, I’ll check it out.  I’ve been having issues testing on Windows (since I don’t know many people who use that operating system) so it will be very helpful.  Travis has been a godsend.

I’ll let you know if I encounter any issues, but I think things should be good.  Thank you again for transferring these packages over.  It’s nice not to need to duplicate someone else’s good work.

Cheers,
Angeline

**Comment by cmeeren** [comment]
Yep. And if you want to directly integrate the code into other packages, you're welcome to for my part.

Oh, and just a quick cc to @klaundal so he knows I don't have anything more to do with apexpy.

**Comment by cmeeren** [comment]
I've added you as a maintainer on readthedocs now. I can't seem to remove myself - could you remove me from both packages?

**Comment by aburrell** [comment]
Hi @klaundal, I'll be sure to let you know if there's anything I need.  

@cmeeren, I took you off of the readthedocs.  Thanks for handing everything over.  

Cheers,
Angeline
