### ISSUE TITLE
Question: MLT definition

### ISSUE THREAD

**Issue by gregstarr** [aburrell/apexpy#79]
**Describe the problem or ask the question**
In `apexpy`, [MLT is defined using the Apex/QD longitude of the subsolar point](https://github.com/aburrell/apexpy/blob/main/src/apexpy/apex.py#L524). In [Magnetic Coordinate Systems - Laundal - 2016](https://arxiv.org/ftp/arxiv/papers/1611/1611.10321.pdf)(section 6) they suggest using the CD longitude instead because it reduces the variability of the coordinate system's rotation rate. Is this modification worth making? This issue is a bit nit-picky, it's just something I noticed, so I thought I would mention it.

**Comment by klaundal** [comment]
I obviously support making the modification :)

I have implemented the technique in the pyAMPS module. Feel free to use what you want if you decide to do something about it. See mlt_utils.py here: https://github.com/klaundal/pyAMPS/tree/master/pyamps 
(I just realized that the header of that file may not be accurate any longer, since I haven't followed apexpy updates that closely recently. It's certainly not necessary information, so I'll fix it... )

**Comment by aburrell** [comment]
Note: CD = centered dipole

https://github.com/klaundal/pyAMPS/blob/7b1be1f3a45fb11acaa7fce98c08370e898340db/pyamps/mlt_utils.py#L360

Implementing this would require introducing another set of magnetic coordinates into apexpy.  Linking #96 since this would require a similar amount of work and may/may not be out of scope for the package.

**Comment by klaundal** [comment]
If you decide it is within the scope, feel free to use the code from my dipole module: https://github.com/klaundal/dipole. 
This module in turn depends on the ppigrf Python module (github.com/klaundal/ppigrf), which calculates IGRF without relying on compiled Fortran code.

**Comment by aburrell** [comment]
Closing this, as we decided to stick to providing only the magnetic coordinates available in the apex fortran code.  Noting for others that @klaundal has python code that provides additional magnetic coordinate systems!
